# Generated by Django 4.2.7 on 2025-12-23 12:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pasons', 'Pasons Ecommerce'), ('talabat', 'Talabat Platform')], default='pasons', help_text='Platform this item belongs to', max_length=20)),
                ('item_code', models.CharField(help_text='Item identifier (can have multiple variants with different SKUs)', max_length=50)),
                ('description', models.TextField(help_text='Item name/description')),
                ('pack_description', models.TextField(blank=True, help_text='Pack description/details', null=True)),
                ('units', models.CharField(help_text='Unit of measurement (e.g., pcs, kg, ltr)', max_length=20)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100)),
                ('barcode', models.CharField(blank=True, help_text='Product barcode', max_length=50, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] Use ItemOutlet.outlet_selling_price instead', max_digits=10)),
                ('stock', models.IntegerField(default=0, help_text='[DEPRECATED] Use ItemOutlet.outlet_stock instead. Cannot be negative.', validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] Use ItemOutlet fields instead. Cannot be negative.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mrp', models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] Use ItemOutlet.outlet_mrp instead. Cannot be negative.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('wrap', models.CharField(blank=True, choices=[('9900', '9900'), ('10000', '10000')], help_text='Wrap code (allowed: 9900 or 10000)', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Wrap must be 9900 or 10000.', regex='^(9900|10000)$')])),
                ('weight_division_factor', models.DecimalField(blank=True, decimal_places=4, help_text='Price division factor for weight-based items (e.g., 2 means price/2). Used to calculate selling price from ERP base price.', max_digits=10, null=True)),
                ('converted_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Converted cost = cost / weight_division_factor. Auto-calculated when weight_division_factor is set.', max_digits=10, null=True)),
                ('outer_case_quantity', models.IntegerField(blank=True, help_text='Outer case pack quantity (e.g., 9 pcs per case). Used for stock validation: stock_qty / outer_case_qty must be >= 1', null=True)),
                ('minimum_qty', models.IntegerField(blank=True, help_text='Minimum order/stock quantity threshold (e.g., 3 = minimum 3 units required for orders)', null=True)),
                ('talabat_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Custom Talabat margin percentage (optional). If not set, defaults: 9900xxx=17%, 100xxx=15%', max_digits=5, null=True)),
                ('price_locked', models.BooleanField(default=False, help_text='Lock price updates at item level')),
                ('status_locked', models.BooleanField(default=False, help_text='Lock status changes at item level')),
                ('is_active', models.BooleanField(default=True, help_text='Active status of the item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('store_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('platforms', models.CharField(choices=[('pasons', 'Pasons Ecommerce'), ('talabat', 'Talabat Platform')], default='pasons', help_text='Platform where this outlet is available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'platforms')},
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('pasons', 'Pasons'), ('talabat', 'Talabat'), ('global', 'Global')], default='pasons', max_length=20)),
                ('update_type', models.CharField(choices=[('product', 'Product Update'), ('stock', 'Stock Update'), ('price_cost', 'Price Update (Cost)'), ('price_mrp', 'Price Update (MRP)'), ('price_both', 'Price Update (Both)'), ('rules_price', 'Rules Update (Price/Margin)'), ('rules_stock', 'Rules Update (Stock)'), ('bulk_creation', 'Bulk Item Creation'), ('promotion_update', 'Promotion Update')], max_length=20)),
                ('records_total', models.IntegerField(default=0)),
                ('records_success', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='JSON data including created_skus, updated_skus for report generation', null=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.outlet')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload History',
                'verbose_name_plural': 'Upload Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_stock', models.IntegerField(default=0, help_text='Stock quantity for this outlet. Cannot be negative.', validators=[django.core.validators.MinValueValidator(0)])),
                ('outlet_cost', models.DecimalField(blank=True, decimal_places=3, help_text='Outlet-specific cost. Cannot be negative.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('outlet_mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Outlet-specific MRP (optional). Cannot be negative.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('outlet_selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Outlet-specific selling price (optional). Cannot be negative.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active_in_outlet', models.BooleanField(default=True, help_text='Whether item is active in this outlet')),
                ('price_locked', models.BooleanField(default=False, help_text='Lock price updates for this outlet')),
                ('status_locked', models.BooleanField(default=False, help_text='Lock status changes for this outlet')),
                ('data_hash', models.CharField(blank=True, db_index=True, help_text='MD5 hash of (mrp|cost|stock) for O(1) change detection. Auto-updated on save.', max_length=32, null=True)),
                ('export_selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Last exported selling_price. Used for delta export detection.', max_digits=10, null=True)),
                ('export_stock_status', models.IntegerField(blank=True, choices=[(0, 'Disabled'), (1, 'Enabled')], help_text='Last exported stock_status (0=disabled, 1=enabled). Used for delta export detection.', null=True)),
                ('erp_export_price', models.DecimalField(blank=True, decimal_places=2, help_text='Last exported ERP price (converted). Used for ERP delta export detection.', max_digits=10, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Input promotional price (base price before conversion)', max_digits=10, null=True)),
                ('converted_promo', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated promotional price after platform/wrap conversion', max_digits=10, null=True)),
                ('original_selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Backup of original selling price before promotion (for restoration)', max_digits=10, null=True)),
                ('promo_start_date', models.DateTimeField(blank=True, help_text='Promotion start date and time', null=True)),
                ('promo_end_date', models.DateTimeField(blank=True, help_text='Promotion end date and time', null=True)),
                ('is_on_promotion', models.BooleanField(default=False, help_text='Whether item is currently on promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_outlets', to='integration.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_items', to='integration.outlet')),
            ],
            options={
                'verbose_name': 'Item-Outlet Association',
                'verbose_name_plural': 'Item-Outlet Associations',
                'ordering': ['item__item_code', 'outlet__name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='outlets',
            field=models.ManyToManyField(help_text='Outlets where this item is available', related_name='items', through='integration.ItemOutlet', to='integration.outlet'),
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pasons', 'Pasons'), ('talabat', 'Talabat')], help_text='Platform for this outlet', max_length=20)),
                ('export_type', models.CharField(choices=[('full', 'Full Export'), ('partial', 'Partial Export - Delta sync')], help_text='Full export or partial delta export', max_length=20)),
                ('export_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact time when export completed (= current DB time at export completion)')),
                ('item_count', models.IntegerField(default=0, help_text='Total items included in this export (for validation)')),
                ('file_name', models.CharField(blank=True, help_text='Generated CSV filename', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success - File generated'), ('failed', 'Failed - No file created'), ('validation_failed', 'Validation Failed - Data issues')], default='success', help_text='Whether export succeeded or failed', max_length=20)),
                ('validation_errors', models.TextField(blank=True, help_text='JSON array of validation errors found during export', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered export (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(help_text='Which outlet was exported', on_delete=django.db.models.deletion.CASCADE, related_name='export_histories', to='integration.outlet')),
            ],
            options={
                'verbose_name': 'Export History',
                'verbose_name_plural': 'Export Histories',
                'ordering': ['-export_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ERPExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('full', 'Full Export'), ('partial', 'Partial Export - Delta sync')], help_text='Full export or partial delta export', max_length=20)),
                ('export_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact time when export completed')),
                ('item_count', models.IntegerField(default=0, help_text='Total items included in this export')),
                ('file_name', models.CharField(blank=True, help_text='Generated CSV filename', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success - File generated'), ('failed', 'Failed - No file created'), ('validation_failed', 'Validation Failed - Data issues')], default='success', help_text='Whether export succeeded or failed', max_length=20)),
                ('validation_errors', models.TextField(blank=True, help_text='JSON array of validation errors found during export', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(help_text='Which outlet was exported', on_delete=django.db.models.deletion.CASCADE, related_name='erp_export_histories', to='integration.outlet')),
            ],
            options={
                'verbose_name': 'ERP Export History',
                'verbose_name_plural': 'ERP Export Histories',
                'ordering': ['-export_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='itemoutlet',
            index=models.Index(fields=['outlet', 'item'], name='integration_outlet__f63140_idx'),
        ),
        migrations.AddIndex(
            model_name='itemoutlet',
            index=models.Index(fields=['item'], name='integration_item_id_28a2b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemoutlet',
            unique_together={('item', 'outlet')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['platform', 'is_active'], name='integration_platfor_d37443_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['platform', 'item_code', 'units'], name='integration_platfor_86d99a_idx'),
        ),
        migrations.AddIndex(
            model_name='exporthistory',
            index=models.Index(fields=['outlet', 'platform', '-export_timestamp'], name='integration_outlet__b5aad2_idx'),
        ),
        migrations.AddIndex(
            model_name='exporthistory',
            index=models.Index(fields=['outlet', 'status'], name='integration_outlet__67614c_idx'),
        ),
        migrations.AddIndex(
            model_name='erpexporthistory',
            index=models.Index(fields=['outlet', '-export_timestamp'], name='integration_outlet__4e3ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='erpexporthistory',
            index=models.Index(fields=['outlet', 'status'], name='integration_outlet__c1435c_idx'),
        ),
    ]
