# Generated by Django 4.2.7 on 2025-12-24 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pasons', 'Pasons'), ('talabat', 'Talabat')], help_text='Platform for this outlet (for isolation verification)', max_length=20)),
                ('reset_type', models.CharField(choices=[('prices_only', 'Reset Prices Only'), ('stock_only', 'Reset Stock Only'), ('complete_reset', 'Complete Reset'), ('unassign_items', 'Unassign Items')], help_text='Type of reset operation performed', max_length=20)),
                ('items_affected', models.IntegerField(default=0, help_text='Total number of ItemOutlet records affected by reset')),
                ('items_success', models.IntegerField(default=0, help_text='Number of items successfully reset')),
                ('items_failed', models.IntegerField(default=0, help_text='Number of items that failed to reset')),
                ('total_price_value_reset', models.DecimalField(decimal_places=2, default=0, help_text='Total monetary value of prices that were reset to zero', max_digits=15)),
                ('total_stock_value_reset', models.IntegerField(default=0, help_text='Total stock quantity that was reset to zero')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', help_text='Status of the reset operation', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the reset operation started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the reset operation completed (success or failure)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if reset operation failed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why reset was performed (data corruption details)', null=True)),
                ('outlet', models.ForeignKey(help_text='Which outlet was reset', on_delete=django.db.models.deletion.CASCADE, related_name='reset_logs', to='integration.outlet')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the reset operation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outlet Reset Log',
                'verbose_name_plural': 'Outlet Reset Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['outlet', 'platform', '-started_at'], name='integration_outlet__68c786_idx'), models.Index(fields=['performed_by', '-started_at'], name='integration_perform_91e4dd_idx'), models.Index(fields=['status', '-started_at'], name='integration_status_9574dd_idx')],
            },
        ),
    ]
