# Generated by Django 4.2.7 on 2025-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='response_data',
            field=models.JSONField(blank=True, null=True, default=dict, help_text='JSON data including created_skus, updated_skus for report generation'),
        ),
    ]
