# Generated by Django 4.2.7 on 2025-12-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_add_outlet_reset_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='E-commerce API URL for pushing product data', null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key/Token for authentication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='pasons_live_store_id',
            field=models.CharField(blank=True, help_text='Store ID for pasons.live e-commerce platform', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='push_enabled',
            field=models.BooleanField(default=False, help_text='Enable API push for this outlet'),
        ),
    ]
