# Generated by Django 4.2.7 on 2025-12-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0003_fix_uploadhistory_response_data_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoutlet',
            name='erp_export_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last exported ERP price (converted). Used for ERP delta export detection.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ERPExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('full', 'Full Export'), ('partial', 'Partial Export - Delta sync')], help_text='Full export or partial delta export', max_length=20)),
                ('export_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact time when export completed')),
                ('item_count', models.IntegerField(default=0, help_text='Total items included in this export')),
                ('file_name', models.CharField(blank=True, help_text='Generated CSV filename', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success - File generated'), ('failed', 'Failed - No file created'), ('validation_failed', 'Validation Failed - Data issues')], default='success', help_text='Whether export succeeded or failed', max_length=20)),
                ('validation_errors', models.TextField(blank=True, help_text='JSON array of validation errors found during export', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(help_text='Which outlet was exported', on_delete=django.db.models.deletion.CASCADE, related_name='erp_export_histories', to='integration.outlet')),
            ],
            options={
                'verbose_name': 'ERP Export History',
                'verbose_name_plural': 'ERP Export Histories',
                'ordering': ['-export_timestamp'],
                'indexes': [models.Index(fields=['outlet', '-export_timestamp'], name='integration_outlet__4e3ad7_idx'), models.Index(fields=['outlet', 'status'], name='integration_outlet__c1435c_idx')],
            },
        ),
    ]
