# Generated by Django 5.1.6 on 2026-03-06 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_add_oauth_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='pasons', max_length=20)),
                ('push_type', models.CharField(choices=[('full', 'Full Push'), ('partial', 'Partial Push - Delta sync')], default='full', max_length=10)),
                ('push_mode', models.CharField(choices=[('normal', 'Normal Prices'), ('offer', 'Offer Prices')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('item_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('push_timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_histories', to='integration.outlet')),
            ],
            options={
                'verbose_name': 'Push History',
                'verbose_name_plural': 'Push Histories',
                'ordering': ['-push_timestamp'],
                'indexes': [models.Index(fields=['outlet', '-push_timestamp'], name='integration_outlet__dfd200_idx'), models.Index(fields=['status', '-push_timestamp'], name='integration_status_92c411_idx'), models.Index(fields=['platform', '-push_timestamp'], name='integration_platfor_38fb2e_idx')],
            },
        ),
    ]
