# Generated by Django 4.2.7 on 2025-12-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_itemoutlet_erp_export_price_erpexporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoutlet',
            name='converted_promo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated promotional price after platform/wrap conversion', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemoutlet',
            name='is_on_promotion',
            field=models.BooleanField(default=False, help_text='Whether item is currently on promotion'),
        ),
        migrations.AddField(
            model_name='itemoutlet',
            name='original_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Backup of original selling price before promotion (for restoration)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemoutlet',
            name='promo_end_date',
            field=models.DateField(blank=True, help_text='Promotion end date', null=True),
        ),
        migrations.AddField(
            model_name='itemoutlet',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Input promotional price (base price before conversion)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemoutlet',
            name='promo_start_date',
            field=models.DateField(blank=True, help_text='Promotion start date', null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['platform', 'item_code', 'units'], name='integration_platfor_86d99a_idx'),
        ),
    ]
