# Generated by Django 4.2.7 on 2025-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_itemoutlet_converted_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoutlet',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, help_text='Promotion end date and time', null=True),
        ),
        migrations.AlterField(
            model_name='itemoutlet',
            name='promo_start_date',
            field=models.DateTimeField(blank=True, help_text='Promotion start date and time', null=True),
        ),
    ]
