# Generated by Django 4.2.7 on 2025-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_alter_itemoutlet_promo_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='update_type',
            field=models.CharField(choices=[('product', 'Product Update'), ('stock', 'Stock Update'), ('price_cost', 'Price Update (Cost)'), ('price_mrp', 'Price Update (MRP)'), ('price_both', 'Price Update (Both)'), ('rules_price', 'Rules Update (Price/Margin)'), ('rules_stock', 'Rules Update (Stock)'), ('bulk_creation', 'Bulk Item Creation'), ('promotion_update', 'Promotion Update')], max_length=20),
        ),
    ]
